language: R
sudo: false
cache: packages
env:
  matrix:
    secure: fqfNBeMSYJdyOKh++v7SMzXzfHbR5XnT8pqq/sM/fbFcg2gD4kHRy2XdD3rETNrr/A61UP7BBaMgmACxqQRh1squ8l7Mzmg1UaxDb5ewFzd1Qbbh0N9QEfG5xZXIpzmTlZiZXKEOwZETK0F2kkzjCQqxqDKfkZ/i6GjGWusJwsHOxOol3bNlO/tqtrlAPQc3WqVZyFFVeovcwLcpllVTPPCLHUWCTgW+WYPxULuvWS4miRFFkuS9mq/wJmswEA11J/g2RPKZnV+1HtMGC5JOXZc4Z6cAp4r8juGuFwwpYpKVO76N/n8BCzJ1Dl69Ibo8d9F+DA9n6hOxVxbaZLLqgH5fm6hOz380Te1GvgkG5c5kPFNaH1GFAtKkBzCEBAnCHoM44Y66BmI4ou3slixRcy8ycaG+p1HoBm0kG4/1TxStVn9Ll4jhoqU113b7g6JEoL0+raI/L8j+Wk2JyFak6JeJX/QKimQ3TIgZpFy4beygAiiNDLa8roX4J2HPovjRLK5OgotUqcP57l780P1CrgyWsQSDFx0qPLNPoFi8IL2Tj22yUKizUxyE40zkrzc1XuDrVPxejfieLClHJBNChSeqmDxnBI9XPU2AC+KxADvRBfdA325Y9shMRzbXV/2IyerKGLWhVcner/b1C574t49avuKTgVVzyYORYc20Oig=
